[package]
name = "kill_bill"
version = "0.1.0"
authors = ["Paras <sivssdn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"
find_folder = "0.3.0"
